### ISSUE TITLE
pxs2phy Abort trap: 6 error

### ISSUE THREAD

**Issue by JimStarrett** [FePhyFoFum/phyx#103]
Hi

I ran pxs2phy on a batch of nexus files with the command:
for i in *.nexus; do pxs2phy -s ${i%} > ${i%}.phy; done

I received the error message below three times and three files produced were empty. The other ~400 looked good. All of the nexus files were generated from the same program, and there didn't seem to be any obvious problems with the three that resulted in empty files.

Assertion failed: ((int)seqs[i].get_sequence().length() == seqlength), function write_phylip_alignment, file seq_utils.cpp, line 228.
Abort trap: 6

Thanks!

**Comment by josephwb** [comment]
This is due to sequences being of unequal length (i.e., not aligned).

Are these genetic sequences, or morphological? If the latter, are any characters ambiguous e.g. `{0 1}`? If so, that is not yet supported by our alignment reader. Any I don't think phylip format supports it either?

**Comment by JimStarrett** [comment]
Thank you for your response. It is peculiar, all 400+ of these files are DNA alignments in nexus format, output from mafft. When I look at the nexus files in text wrangler, I don't see any special or hidden characters that would prevent these three alignments from being converted to phylip.

**Comment by josephwb** [comment]
Is it possible that these weirdo files have dos or mac line-endings? Because that would mess things up too. You can check/fix this directly in TextWrangler.

**Comment by JimStarrett** [comment]
I looked at a sample of files and it appears the only files that didn't work are ones that were output by mafft in interleaved nexus format, perhaps because they are over 1 Kb in length. Otherwise all of the files have the same Document language (none), Text encoding (Unicode UTF-8), and Line break (Unix).

**Comment by josephwb** [comment]
Ah! Ok. So we need to revisit our processing of interleaved data. Sorry for the difficulty.

Could you send one file to me to troubleshoot? phylo.jwb at gmail.com

**Comment by josephwb** [comment]
It appears that interleaved data got left as a TODO, possibly bc it doesn't quite work with the philosophy of streaming one sequence at a time (all sequences must first be read in before any sequence can be processed). 
I'll try to get this fixed today.
If you cannot wait, you can use [paup](http://phylosolutions.com/paup-test/) to do this:
```
exe FILENAME.nex;
export format=phylip charsPerLine=all file=FILENAME.phy;
```

**Comment by josephwb** [comment]
Still working on the `pxs2*` bits, but the reader is complete. You can get things to work by piping:
```
pxcat -s MY_INTERLEAVED_FILE.NEX  | pxs2phy -o MYFILE.phy
```

**Comment by coyotree** [comment]
> 
> 
> Still working on the `pxs2*` bits, but the reader is complete. You can get things to work by piping:
> 
> ```
> pxcat -s MY_INTERLEAVED_FILE.NEX  | pxs2phy -o MYFILE.phy
> ```

Hi Joseph,
I just tried doing this but it spits out the error:
/apps/phyx/0.99/launch_phyx: line 12: 10086 Segmentation fault      singularity exec ${HPC_SINGULARITY_IMG}/phyx/0.99-xenial.img "$@"

**Comment by josephwb** [comment]
Did you:
```
git pull && make && sudo make install
```
I just tried on a fresh clone and it worked with your file.

JWB

**Comment by coyotree** [comment]
Hi Joseph,

Sorry, I'm using phyx on a cluster and forgot that they need to update it.

**Comment by josephwb** [comment]
@coyotree Make sure to include `make clean` in the (edited) command above. I pushed a bunch of (minor) stuff today that needs complete recompilation. You can check if things work properly by running:
```
python run tests.py
```

**Comment by josephwb** [comment]
Ok, interleaved Nexus is supported by all of the pxs2* programs as of 59d556882f2c997c85dfed722337713b813b79c5. e.g. your original command of:
```
pxs2phy -s INTERLEAVED.NEX -o FILE.phy
```
should work. Let me know if this works for you, and we can close this puppy. @JimStarrett @coyotree

**Comment by josephwb** [comment]
You can reopen this if it does not meet your expectations.
