### ISSUE TITLE
pxt2nex: command not found

### ISSUE THREAD

**Issue by coyotree** [FePhyFoFum/phyx#104]
Hello,

I am trying to convert a tree file of 100 trees made from treePL to nexus format for input into treeAnnotator. I saw here (https://github.com/josephwb/Newick2Nexus) that 'pxt2nex' was now implemented in phyx but I receive the error "command not found" when trying to use it.

I am using a version of phyx updated on 03 April 2019 on a computing cluster.

The command I am attempting to run is:
`pxt2nex -t tree.file -o outfile`

Thanks,
Cody Coyotee

**Comment by josephwb** [comment]
`make` should make all listed targets. If something fails upstream, then the downstream targets are not compiled. You can do `make pxt2nex` to compile this program specifically. But if things are failing, we should fix that. Let us know of any error messages produced during compiling.

**Comment by coyotree** [comment]
Hi Joseph,

Our IT people had this to say:

"I just git cloned the phyx repo and did a new build. The 'pxt2new' is not
getting built. 

phyx/src$ make pxt2nex
make: *** No rule to make target `pxt2nex'.  Stop.

And running a grep command to find any mention of pxt2nex in the source code
doesn't find anything either:

phyx$ grep -ri "pxt2nex"
phyx$"

**Comment by josephwb** [comment]
Hmm yes I can confirm this. I'll add it in and let you know.

**Comment by josephwb** [comment]
Ok, this is up. To get it installed do:
```
make distclean
git pull
autoconf
./configure
make
make check
```
and assuming that works:
```
sudo make install
```
Let us know if this works.

**Comment by coyotree** [comment]
This worked! Thanks!
