### ISSUE TITLE
Feature request: Support for regex in pxrmt/main_rmt.cpp

### ISSUE THREAD

**Issue by HeatherKates** [FePhyFoFum/phyx#106]
I'd like to be able to do something like:
`pxrmt -t tree.phy -n .*Papilionoideae`
to remove any tip of a certain family if my label names include an ID for the family name in addition to a unique identifier. I know this may not look like a sound way to use pxrmt, but I'm actually removing an entire clade that needs to be included in the analysis as an outgroup (and now I want just the ingroup in the tree). I know functions to extract clades exists in multiple R packages, but it's a lot better for me to use phyx for piping/loops that I'm working with.
Thank you!

**Comment by blackrim** [comment]
That is a good idea. I will tackle that.

**Comment by josephwb** [comment]
Similar to https://github.com/FePhyFoFum/phyx/issues/59. I've gone back and forth on whether we need regex, as that can be done at the commandline (see example in other issue), but it might be fun to implement.

**Comment by josephwb** [comment]
Ok I have most of this implemented. Will push later today.

**Comment by josephwb** [comment]
This has been implemented as of 3b51099f196d9f8f82a135eb1d2f12458b019a2d. I've tested it, but further testing welcome.
I'll close this when merging to master.

**Comment by HeatherKates** [comment]
Thanks for doing this! I missed your comment about doing this from the command line before.
