### ISSUE TITLE
Trouble installing in Ubuntu 18.04; error with libnlopt-cxx-dev

### ISSUE THREAD

**Issue by drelo** [FePhyFoFum/phyx#107]
Hi, maybe this is a minor thing but I am installing phyx in a new machine, with Ubuntu 18.04. First I got the error 

`E: Unable to locate package libnlopt-cxx-dev` I don't know if this is available in 18.04 but maybe I am doing something wrong [This machine in the lab should stay under LTS].

I proceeded with the install anyway and I got errors during the run_tests.py step. How could I fix this? Thanks

**Comment by drelo** [comment]
> Did you follow [these](https://github.com/FePhyFoFum/phyx/wiki/Installation#linux-install) instructions? It includes installation of the nlopt dependency.
> 

@josephwb , the main page https://github.com/FePhyFoFum/phyx still has the problematic instructions  to install cxxx-dev, I just noticed this because in another machine at the lab I left that tab open and started to install/build from there.

**Comment by josephwb** [comment]
Hmm I actually do not know if we need libnlopt-cxx-dev. Do you @blackrim?

**Comment by blackrim** [comment]
It uses it for optimization I believe still.

**Comment by josephwb** [comment]
Hrm ok my apt-get (Ubuntu 18) does not even have that package or anything similar.

**Comment by Cactusolo** [comment]
Hi, just follow up, I have the same issue, before I `git clone phy repo`:

~/apps$ sudo apt install libnlopt-cxx-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libnlopt-cxx-dev

I also tried suggestions from [here](https://askubuntu.com/questions/1183467/e-unable-to-locate-package-libnlopt-cxx-dev/1183510#1183510)

But no luck.

Thanks!


I am running ` Operating System: Ubuntu 18.04.3 LTS`

**Comment by josephwb** [comment]
I have not been able to find `libnlopt-cxx-dev`. Trusn out you don't need it anyway. Omit that dependency, then do:
```
./configure
make
make check
```
to confirm things work. If so, please report here, and I will just take that dependency out of the docs.

**Comment by josephwb** [comment]
Thanks. It is [gone](https://github.com/FePhyFoFum/phyx/commit/e0260d20d3d5a4d4d88c3b0e16f78f2472a19b9e).
