### ISSUE TITLE
Move over to python3

### ISSUE THREAD

**Issue by shayandoust** [FePhyFoFum/phyx#109]
Hello,

With the deprecation of python2 approaching soon, we generally encourage upstream developers to port over any python2 files they have to python3. This is becoming a mandatory requirement within debian. For instance, this [bug report] opened against phyx.

Currently, we have created a [patch] to which we have used the 2to3 tool to recursively traverse all directories and port over to python3. It is therefore advised that any python files are ported over to python3 within this github repository to eventually eliminate the need for such patch. This will significantly lower both potential packaging / porting errors and maintainer time investment.

Thanks,
Shayan Doust

[bug report]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=937285
[patch]: https://salsa.debian.org/med-team/phyx/blob/master/debian/patches/2to3.patch

**Comment by josephwb** [comment]
Thanks for the report. `Phyx_Gui.py` was a toy, and is not being developed. It is safe to remove (we will do the same with the master branch).

**Comment by josephwb** [comment]
Done.
