### ISSUE TITLE
Documentation for all the tools?

### ISSUE THREAD

**Issue by tseemann** [FePhyFoFum/phyx#112]
I am struggling to find documentation for all the `phyx` tools.
Can you help me?

**Comment by tseemann** [comment]
UPDATE: 
i found a PDF Manual in the `doc` dir on github.
But I don't think this is linked to anywhere on README.md?
Also, can we please have a Markdown (or HTML) version of it please?

**Comment by josephwb** [comment]
The wiki is [here](https://github.com/FePhyFoFum/phyx/wiki).

**Comment by josephwb** [comment]
I should note that both the manual and wiki are a bit out of date. I will endeavour to update them.

**Comment by tseemann** [comment]
@josephwb thank you for being polite in the face of my inability to read correctly the first paragraph of your README . i looked twice and didn't see it, sorry.

_phyx performs phylogenetics analyses on trees and sequences. See installation instructions for Linux and Mac including any dependencies on the wiki here or below. A list of the current programs with examples can be found here. See a brief overview here._

**Comment by josephwb** [comment]
Haha. No problem. It really _should_ have its own heading to be easier to find. We'll try to make things clearer.

**Comment by josephwb** [comment]
Hopefully things are [more easily visible now](https://github.com/FePhyFoFum/phyx/blob/master/README.md). Documentation still needs a thorough updating, but the important stuff is there.

**Comment by tseemann** [comment]
Thank you @josephwb - it is much clearer now.
