### ISSUE TITLE
pxtgen not found in current repo

### ISSUE THREAD

**Issue by michael-branstetter** [FePhyFoFum/phyx#128]
The manual says this function should be available now, but I can't find it after updating. Is this still in development?

**Comment by josephwb** [comment]
Try:
```
make clean
git pull
autoreconf -fi
./configure
make
```
and `sudo make install` if you want to install it.

Let us know if this works.

**Comment by michael-branstetter** [comment]
That did not work. When I entered "git pull", it returned "Already up to
date."

Michael

---------------------------------------------------------
Michael Branstetter, PhD
USDA-ARS Pollinating Insects Research Unit
Utah State University
5310 Old Main Hill
Logan, UT 84322-5310
(435) 797-2588
---------------------------------------------------------

**Comment by josephwb** [comment]
Ah ok. You have all the files, you just need to generate the Makefile.

Try the remaining commands above. You can even do `make pxtgen` to just make that one program.

**Comment by michael-branstetter** [comment]
I did go through all of the commands after git pull and pxtgen still did
not compile. Typing "make pxtgen" separately did work, however, so problem
solved.

Thanks,
Michael

---------------------------------------------------------
Michael Branstetter, PhD
USDA-ARS Pollinating Insects Research Unit
Utah State University
5310 Old Main Hill
Logan, UT 84322-5310
(435) 797-2588
---------------------------------------------------------

**Comment by josephwb** [comment]
Hmm. Try:
```
make distclean
autoreconf -fi
./configure
make -j
```

**Comment by josephwb** [comment]
Hrm I cannot recreate this. I cloned a very old version of the repo, built, pulled, and rebuild again and everything is as it should be. I am baffled. Obviously you have the code _and_ the compile command in your Makefile, but it feels like `pxtgen` is not part of the default build.

Can you please report the results of (from the src dir): 
```
grep -n pxtgen Makefile
```
Mt results are:
```
340:PROGS := pxmrca pxmrcacut pxmrcaname pxconsq pxbdsim pxlstr pxlssq pxupgma pxclsq pxcltr pxs2fa pxs2phy pxs2nex pxfqfilt pxrevcomp pxnw pxsw pxboot pxcat pxsstat pxrecode pxbp pxt2new pxt2nex pxrr pxmono pxaa2cdn pxtlate pxrms pxrmt pxtrt pxrmk pxnj pxlog pxvcf2fa pxrlt pxrls pxtscale pxstrec pxseqgen pxssort pxcontrates pxtcol pxtcomb pxtgen pxssort pxcolt pxcomp $(NLOPT_PROGRAMS)
584:pxtgen: $(CPP_OBJS) $(TGEN_OBJ)
585:	@echo 'building pxtgen'
586:	$(CXX) -o "pxtgen" $(OPT_FLAGS) $(TGEN_OBJ) $(CPP_OBJS)
```
That first line (`PROGS`) lists the default build, which contains `pxtgen`. 

If you are missing the `PROGS` line above, does this find it:
```
grep -n pxtgen Makefile.in
```
If so, something went wrong with configure.

If you are missing that line in any of your results, it _must_ be some old commit in between implementing the method and adding it to the default build.

**Comment by josephwb** [comment]
Since I cannot recreate this I'm going to close this for now. Please re-open if new information surfaces.
