### ISSUE TITLE
pxt2new terminate called after throwing an instance of 'std::out_of_range'

### ISSUE THREAD

**Issue by Cactusolo** [FePhyFoFum/phyx#130]
Hi,

I'm trying to convert the nexus format to newick using `pxt2new` function. 

**Here is the cmd:**
`pxt2new -t Magallon_etal_PL_ML.nex -o test.tre`

_the input tree can be found [here](https://datadryad.org/stash/dataset/doi:10.5061/dryad.k4227)._

**Here is the error msg:**
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 18446744073709551615) > this->size() (which is 0)
Aborted (core dumped)

**I believe the program is successfully installed.**
` pxt2new -h`

This will convert a tree file to newick.
This will take a newick- or nexus-formatted tree from a file or STDIN.

Usage: pxt2new [OPTIONS]...

Options:
 -t, --treef=FILE    input tree file, STDIN otherwise
 -o, --outf=FILE     output tree file, STOUT otherwise
 -h, --help          display this help and exit
 -V, --version       display version and exit
 -C, --citation      display phyx citation and exit

Report bugs to: <https://github.com/FePhyFoFum/phyx/issues>
phyx home page: <https://github.com/FePhyFoFum/phyx>

_**Please help.**_

Miao

**Comment by josephwb** [comment]
It looks like this is the result of a Nexus comment within the Begin trees block. I thought this was covered, but I guess not. I will fix it right away.

For the moment you can just delete the 6th line `[TREE DESCRIPTION of tree PAUP_1]`.

**Comment by josephwb** [comment]
Fixed with 17bb570e6072b0b56ca85aaf90e2e8dc24c8b772. Thanks for reporting it.
