### ISSUE TITLE
treereader produces incorrect tree when input contains illegal characters

### ISSUE THREAD

**Issue by HeatherKates** [FePhyFoFum/phyx#132]
[Fagales_root_list.txt](https://github.com/FePhyFoFum/phyx/files/4886169/Fagales_root_list.txt)
[Fagales_Drop_list.txt](https://github.com/FePhyFoFum/phyx/files/4886255/Fagales_Drop_list.txt)
[Fagales_CAML.pxrlt.txt](https://github.com/FePhyFoFum/phyx/files/4886257/Fagales_CAML.pxrlt.txt)

Run commands (either output tree has (a) polytomy/ies): 
`pxrr -g ``more Fagales_root_list.txt|tr '\n' ','`` -t Fagales_CAML.pxrlt.tree -o Fagales_CAML.pxrlt.pxrr.tree`
`pxrmt -f Fagales_Drop_list.txt -t Fagales_CAML.pxrlt.tree -o Fagales_CAML.pxrlt.pxrmt.tree`

Thank you for letting me know what this may be!  (.tree uploaded as .txt for github). The `` in the code snippet is `
Heather Rose

**Comment by josephwb** [comment]
I will look at this. Sorry for the delay.

**Comment by josephwb** [comment]
Hrm something is seriously wrong (with the tree reader, I believe). Trying to come up with a more manageable example to troubleshoot.

**Comment by josephwb** [comment]
Minor progress on this: when I run the tree through ape (i.e., just read in, write out) the resulting tree works fine in `pxrr`. So it is something about the tree string itself...

**Comment by josephwb** [comment]
AH!

Ok, this is simple. Two of the terminal labels contains a newick-illegal character:

Fagales_NA_NA_Fagaceae_NA_Quercus_brandeg[e]ii
Fagales_NA_NA_Fagaceae_NA_Quercus_margarett[i]ae

Phyx interprets "[" as an annotation, thus terminating the labels, storing the bits in square brackets as annotations, an creating new nodes (without branch lengths) for the remainder of the label.

If 1) the square brackets are removed or 2) theses labels have quotes are them (i.e., "Fagales_NA_NA_Fagaceae_NA_Quercus_brandeg[e]ii") then everything works perfectly.

I am so sorry it took so long to figure this out @HeatherKates! I've picked this up so many times only to give up being thoroughly frustrated.

This should be handled better, as obviously R (ape) and FigTree do not have a problem. Incidentally, FigTree puts the label in single quotes on export:

'Fagales_NA_NA_Fagaceae_NA_Quercus_margarett[i]ae'

 while R just gets rid of the bits in brackets altogether as if it were a comment:

Fagales_NA_NA_Fagaceae_NA_Quercus_margarettae

I'll close this once I figure out the best way to deal deal with it. We [have code to ensure that exported labels are compliant](https://github.com/FePhyFoFum/phyx/blob/master/src/utils.cpp#L530-L585); need to use this on import as well.

**Comment by josephwb** [comment]
Kicking myself for not considering this earlier... It is almost _always_ line endings or invalid characters... 

( ╯°□°)╯ ┻━━┻

**Comment by josephwb** [comment]
Hrm not sure how to "fix" this. We cannot allow illegal characters (()[]{}/\\,;:=*\'\"`+-<>) in taxon/node labels. The offending characters here were '[' and ']'. MrBayes and FigTree may put annotations (bounded by '[' and ']') at the end of terminal labels, so we cannot allow them within unquoted labels. I presume that ape reads a tree like the one above by removing all "comments" on a first pass before processing the tree. Obviously we do not want to do this. 
I'm afraid this falls in the "wontfix" category; we need to trust that the user is passing in legitimate input. Still, it would be nice to be able to detect and report when a tree is not compliant. I'm not sure how to do this. We were "lucky" with the tree above that the offending characters were paired so the reader did not crash altogether.
Closing this and creating a more nuanced issue.

**Comment by HeatherKates** [comment]
Hi Joseph, thanks for looking so carefully at this. I had found/fixed those labels in other analyses...missed this one! So this error actually had nothing to do with anything important or likely to recur. My mistake.

**Comment by josephwb** [comment]
@HeatherKates  No worries! Good to know that this type of thing can arise, and we should find a way to deal with it.I am just sorry it took so long to realize it on my end.
