### ISSUE TITLE
pxsw does not print out to file

### ISSUE THREAD

**Issue by jfwalker** [FePhyFoFum/phyx#15]

**Comment by josephwb** [comment]
Can you paste some example data and commands to recreate the problem? :bowtie:

**Comment by jfwalker** [comment]
Any fasta file should recreate the problem, it only creates the files for output it does not put anything into them
[aatest.zip](https://github.com/FePhyFoFum/phyx/files/196405/aatest.zip)

**Comment by josephwb** [comment]
Fixed.
