### ISSUE TITLE
pxrr loses certain taxa names

### ISSUE THREAD

**Issue by jfwalker** [FePhyFoFum/phyx#16]
When trying to reroot, one of the taxa names is not printed out to the rerooted tree
cmd: ./pxrr -t cluster5535.tre -g Beta,Spol
[cluster5535.tre.zip](https://github.com/FePhyFoFum/phyx/files/200261/cluster5535.tre.zip)

**Comment by josephwb** [comment]
Weird. Tree is rooted correctly, taxon is "there", just no name:
```
((Beta:45.5,Spol:45.5):225.375,(((Dimu:34.875,MJM1652:40.125):14.75,DrobinSFB:60.25):17.5,(DrolusSFB:64.25,:61.75):10.75):225.375);
                                                                                                           ^
```

**Comment by josephwb** [comment]
Same if only specifying one outgroup:
`./pxrr -t cluster5535.tre -g Beta`

**Comment by jfwalker** [comment]
All the trees seem to root just fine but one of the taxon names disappears

**Comment by josephwb** [comment]
I fixed it for this example:
```
./pxrr -t cluster5535.tre -g Beta,Spol
((Beta:45.5,Spol:45.5):225.375,(((Dimu:34.875,MJM1652:40.125):14.75,DrobinSFB:60.25):17.5,(NepSFB:61.75,DrolusSFB:64.25):10.75):225.375);
```
but may have broken it for others. I will look closer at this later, but this is the commit: https://github.com/FePhyFoFum/phyx/commit/c859e8d9ef2d4ed7ccf8dacd8bc4aebbdd99140c

As you can see I just reversed something that @blackrim had done (which makes me think this will break other things his change had fixed).

**Comment by josephwb** [comment]
From @jfwalker's testing this seems to be fixed. Closing for now.
