### ISSUE TITLE
How to install phyx on linux without root access ? 

### ISSUE THREAD

**Issue by Galaxy-228** [FePhyFoFum/phyx#169]

**Comment by josephwb** [comment]
By default it installs deep in the system (hence, root access). You can instead install it somewhere else that does not require such privileges. Normally this is your home directory. Try this:
```
make distclean
autoreconf -fi
./configure --prefix=$HOME
make
make check
make install
```
HTH.

**Comment by liujie19932288** [comment]
Thank u so much!!! 
I have tried 'make distclean ....' , but it doesn't work in my server .
Is it feasible if I install with Conda ? (Version：phyx = 1.1).

**Comment by Galaxy-228** [comment]
Thank u so much!!!
I have tried 'make distclean ....' , but it doesn't work in my server .
Is there anything wrong if I install with Conda ? (Version：phyx = 1.1).

**Comment by josephwb** [comment]
Well, some bugs have been fixed since then, but it should be good?

**Comment by josephwb** [comment]
What happens if you skip the `make distclean` step. It should still work.

I would recommend communicating with the administrator to get the most recent version installed (v1.3).

**Comment by josephwb** [comment]
Can I close this @Galaxy-228?

**Comment by Galaxy-228** [comment]
Thanks for reply. Please close the issue.
Thanks so much.
