### ISSUE TITLE
pxrr needs better name checker

### ISSUE THREAD

**Issue by josephwb** [FePhyFoFum/phyx#17]
From @jfwalker: `pxrr` segfaults is outgroup not in the tree.

Specifying a single bad outgroup seems to work fine (real outgroup is "Beta"):
```
./pxrr -t cluster5535.tre -g Beta123
the outgroup taxa don't exist in this tree
```
But barfs with 1 good and 1 bad outgroup:
```
./pxrr -t cluster5535.tre -g Beta123,Spol
Segmentation fault
```
Here is the example tree ("cluster5535.tre"):
```
(((((Dimu:34.875000,MJM1652:40.125000):14.750000,DrobinSFB:60.250000):17.500000,(Beta:45.500000,Spol:45.500000):450.750000):10.750000,DrolusSFB:64.250000):30.875000,NepSFB:30.875000);
```

**Comment by josephwb** [comment]
Ok, `tree_utils.cpp` has "check_names_against_tree", which seems to solve this (3fb3e6d05ce10acdda7cfa6aff6cf4f354c0ae0e).

Not sure what the correct return should be here. If an error message is printed, but it is part of a (stream) pipeline, that string will take the place of the newick string, and things will die downstream.

What is the unix-approach to this? Print nothing?

**Comment by josephwb** [comment]
This is what it currently does:
```
./pxrr -t cluster5535.tre -g Beta123,Spol
Taxon 'Beta123' not found in tree.
the outgroup taxa don't exist in this tree 
```

**Comment by jfwalker** [comment]
I think the most helpful is saying Taxon 'Beta123' not found in tree. Anything else might result in troubleshooting until the problem is figured out

**Comment by josephwb** [comment]
Looking for feedback from @blackrim here: if only a subset of outgroup taxa are found, should `pxrr` use these to root the tree and not complain. @jfwalker and I think this is good for p4rocessing a distribution of trees. What if _no_ outgroup taxa are found? Should 1) the tree be returned unaltered or 2) print a complaint?

**Comment by blackrim** [comment]
hm, how do you mean that only a subset are "found"? as in they were misspelled or not all trees are complete? i think the cleanest thing would be to print an error and no tree. then if you want to root with a subset (as in the distribution) there should be another option that suppresses that error and roots with whatever is there (in some cases none). what do you think?

**Comment by josephwb** [comment]
Yeah, I meant trees are incomplete (not typos). Having a separate option sounds like a good idea. Thanks.

**Comment by josephwb** [comment]
I guess I was thinking that in unix if you try to perform some manipulation (e.g. gsub) that has no effect (here, no substitution), the original data is returned unaltered, with no error.
So I wonder which we should do:

1. barf out a error message if any outgroup taxa are not found, _unless_ some sort of "silient" flag is passed.
2. do not print any error messages, _unless_ a "verbose" flag is passed.

**Comment by josephwb** [comment]
Implemented a `silent` flag. This is the way things currently stand: given tree file `foo.tre`:
```
(((((Dimu,MJM1652),DrobinSFB),(Beta123,Spol)),DrolusSFB),NepSFB);
(((((Dimu,MJM1652),DrobinSFB),(Beta,Spol)),DrolusSFB),NepSFB);
(((((Dimu,MJM1652),DrobinSFB),(Beta,Spol123)),DrolusSFB),NepSFB);
```
And outgroups: `Beta123` and `Spol`. Tree 1 has both outgroups, tree 2 has 1, tree 3 has none).
Running without `silent`:
```
./pxrr -t foo.tre -g Beta123,Spol
((Beta123:0,Spol:0):0,(((Dimu:0,MJM1652:0):0,DrobinSFB:0):0,(NepSFB:0,DrolusSFB:0):0):0);
Taxon 'Beta123' not found in tree.
the outgroup taxa don't exist in this tree 
Taxon 'Beta123' not found in tree.
Taxon 'Spol' not found in tree.
the outgroup taxa don't exist in this tree
```
Running it with `silent` turned on gives this:
```
./pxrr -t foo.tre -g Beta123,Spol -s
((Beta123:0,Spol:0):0,(((Dimu:0,MJM1652:0):0,DrobinSFB:0):0,(NepSFB:0,DrolusSFB:0):0):0);
(Spol:0,(Beta:0,(((Dimu:0,MJM1652:0):0,DrobinSFB:0):0,(NepSFB:0,DrolusSFB:0):0):0):0);
(((((Dimu:0,MJM1652:0):0,DrobinSFB:0):0,(Beta:0,Spol123:0):0):0,DrolusSFB:0):0,NepSFB:0);
```
In particular, the 3rd tree is returned unaltered (beyond adding zero edgelengths). Is this what we want? I can see argument for/against.

**Comment by stubbsrl** [comment]
Is there a way to systematically move through the outgroups if the first is absent in one tree to try the second, then the third, etc.?

**Comment by josephwb** [comment]
We've talked about this as an option. A hack option is to loop over your outgroups in _reverse_ order of preference, rooting on one each time. The final rooting would be on the most preferred outgroup that is present in a given tree.

Obviously this is quite hacky! :bowtie:  We'll go ahead and implement the option of an ordered list of outgroups. But then comes the question: if _all_ outgroups are present, do you still want to root on the first?

**Comment by stubbsrl** [comment]
I am trying to root the gene trees for use in PhyParts. Therefore, in this instance I don't really care about the outgroup relationships I just need them to be outgroups (it would be nice if the trees were rooted correctly but it is not really important for me to look at ingroup discordance). I have been inputting my outgroups with the most distant taxa listed first and the sister clade listed last. So, in answer to your question in my case, yes, root on the first taxa listed. 

So, is it a hassle to implement this option? Will it be a qualifier to the pxrr function? Thanks for your help!

**Comment by josephwb** [comment]
@stubbsrl No hassle. I'll implement it today.

**Comment by josephwb** [comment]
@stubbsrl it is now implemented with the `-r` option:
```
./pxrr -h
This will reroot (or unroot) a tree file and produce a newick.
Can read from stdin or file.

Usage: pxrr [OPTION]... [FILE]...

 -t, --treef=FILE     input tree file, stdin otherwise
 -g, --outgroups=CSL  outgroup sep by commas (NO SPACES!)
 -r, --ranked         outgroups are ordered. root on first one present
 -u, --unroot         unroot the tree
 -o, --outf=FILE      output tree file, stout otherwise
 -s, --silent         do not error if outgroup(s) not found
 -h, --help           display this help and exit
 -V, --version        display version and exit
```

**Comment by stubbsrl** [comment]
Awesome! Thanks!!!
