### ISSUE TITLE
pxrlt and pxrls only change the final name on the list

### ISSUE THREAD

**Issue by VaneMorales** [FePhyFoFum/phyx#170]
Hi!
I am new to using this tool and I have been trying to change the names on a tree and a sequence file but every time I try I get the same result. The only name that changes is the last one on the list (Senecio otites V03). Does anyone know why and I can solve this?
![Tree_new_names](https://user-images.githubusercontent.com/109916446/180658184-b22ccfec-ded8-4fe2-9a60-1a7c091a5503.jpg)
![Aligment_new_names](https://user-images.githubusercontent.com/109916446/180658191-fd58cb9d-eddb-4311-bcc5-34f9db1100b6.jpg)

**Comment by josephwb** [comment]
Hi @VaneMorales. Can you please provide example input files and commands you are using? I will take a look at it.

**Comment by josephwb** [comment]
Ok, I will look at this today. Sorry for the problems.

**Comment by josephwb** [comment]
The problem is it is not matching the names in the file. You can use the verbose option (`-v`) to get more information:
```
$ pxrlt -c ITS_numbers_s_otites.txt -n ITS_names_s_otites.txt -t ITS_result.raxml.bestTree -v
The following names to match were not found in the tree:
EF538363.1
GU818665.1
GU818666.1
GU818667.1
GU818668.1
GU818669.1
GU818670.1
Senecio_otites_V1_ITS_consensus_sequence
Senecio_otites_V2_ITS_consensus_sequence
Senecio_otites_V6_ITS_consensus_sequence
Senecio_otites_V7_ITS_consensus_sequence
(((GU818669.1:0.005328,GU818670.1:0.003992):0.000001,(EF538363.1:0.005434,((Senecio_otites_V7_ITS_consensus_sequence:0.000001,(Senecio_otites_V2_ITS_consensus_sequence:0.002144,Senecio_otites_V03:0.000001):0.002113):0.000001,Senecio_otites_V1_ITS_consensus_sequence:0.000001):0.000001):0.000001):0.000001,(GU818666.1:0.001328,(Senecio_otites_V6_ITS_consensus_sequence:0.000001,GU818665.1:0.00133):0.00133):0.000001,(GU818668.1:0.005327,GU818667.1:0.002661):0.000001);
```
But those names _are_ in the tree, so I will have to track down what is going wrong with the matching.

**Comment by VaneMorales** [comment]
Many thanks for looking at this. I was thinking it was because the software added a space after the name when the alignment is exported (*.phy) , but the space does not appear on the tree or in the input files (current and new names of the sequences). It's not about the length of the names used either.

**Comment by josephwb** [comment]
Hey @VaneMorales. Sorry about the delay on this. I have a chunk of time later today when I'll tackle this... or die trying (^_-)≡☆

**Comment by VaneMorales** [comment]
Thank god you are not dead!!! I was starting to be worried. Many thanks for looking into this and for pointing the solution to my problem (I have had several issues as I am running these analyses in Ubuntu but I had managed to fix them until now), so I am very grateful for your help :)

**Comment by josephwb** [comment]
(>ᴗ•)
