### ISSUE TITLE
pxrlt and pxrmt doesn't output tip name with "-" correctly

### ISSUE THREAD

**Issue by fkyeeb** [FePhyFoFum/phyx#171]
for example if the tip name is "Van-royena_castanosperma", the tip name in the output tree will be "'Van-royena castanosperma'".
The underscore will be removed and single quotation marks will be added to either side of the name.

**Comment by josephwb** [comment]
Can you please provide input files and expected output?

**Comment by josephwb** [comment]
Actually, this is a "feature". Names that contain nexus-illegal characters (()[]{}/\,;:=*'"`+-<>) should be single-quoted. Underscores are considered as space-characters in unquoted labels, and so are replaced by literal spaces in the quoted label.

Does that make sense.

**Comment by fkyeeb** [comment]
Yes! Thank you. Then what should I do if I would like the tip name to not change after using phyx, when the tip name has to contain Nexus-illegal characters?

**Comment by josephwb** [comment]
Any name you want to conserve literally, just surround with single quotes. So in your example above, replace:

Van-royena_castanosperma

with

'Van-royena_castanosperma'

and everything should work as expected. Sorry for the headache; some programs are Nexus-compliant, others partially so. :)

**Comment by fkyeeb** [comment]
Thank you for helping!
