### ISSUE TITLE
pxaa2cdn -r not working as expected

### ISSUE THREAD

**Issue by NatJWalker-Hale** [FePhyFoFum/phyx#172]
Hey Joseph,

The new `-r` option to pxaa2cdn appears to not work as expected. Here is a little example case:

[test.cds.fa.txt](https://github.com/FePhyFoFum/phyx/files/9382975/test.cds.fa.txt)
[test.pep.fa.txt](https://github.com/FePhyFoFum/phyx/files/9382976/test.pep.fa.txt)

`pxaa2cdn -r -a test.pep.fa.txt -n test.cds.fa.txt` gives:
`Error: for taxon '1' nucleotide alignment involves 3 codons, but protein alignment involves 2 amino acids. Skipping.`
`Error: for taxon '2' nucleotide alignment involves 3 codons, but protein alignment involves 2 amino acids. Skipping.`

Which is the same output as
`pxaa2cdn -a test.pep.fa.txt -n test.cds.fa.txt`

Seems that `-r` is not actually activating the ignoring of the last codon yet?

Thanks, 

Nat

**Comment by NatJWalker-Hale** [comment]
Having a peak, I think (though could be wrong), that this is because there is no check for `-r` while checking for the mismatch of lengths. I guess that will have to check if they're off by one if `-r` is invoked. I'll try fiddle with it my end and submit a PR if it works, unless you get to it first.

**Comment by josephwb** [comment]
Can confirm. Sorry about that. I will have a look later today. It should take a few minutes, but I am heading out the door.

**Comment by josephwb** [comment]
Ok I see what is going on. Be back soon.

**Comment by josephwb** [comment]
Should be fixed with 9f15c7ae6f2723701b158514dfdb9eb7427064e3

**Comment by NatJWalker-Hale** [comment]
That works! Although I note that it makes the codon count in the error message for mismatching lengths off by one, e.g. 

[test2.cds.fa.txt](https://github.com/FePhyFoFum/phyx/files/9383365/test2.cds.fa.txt)

`pxaa2cdn -r -a test.pep.fa.txt -n test2.cds.fa.txt`
`Error: for taxon '1' nucleotide alignment involves 4 codons, but protein alignment involves 2 amino acids. Skipping.`
`Error: for taxon '2' nucleotide alignment involves 4 codons, but protein alignment involves 2 amino acids. Skipping.`

But `test2.cds.fa.txt` has 5 codons, etc... 

Anyway, I see what you mean about my PR, will close it! Many thanks for dealing with it so quickly.

**Comment by josephwb** [comment]
Erg yes I'll fix the warning.

**Comment by NatJWalker-Hale** [comment]
legend, thanks!
