### ISSUE TITLE
phyx installed

### ISSUE THREAD

**Issue by ChaoShenzjs** [FePhyFoFum/phyx#176]
Hi,
phyx must be made installed under python3?

**Comment by josephwb** [comment]
Python is only used to run the tests. They were updated to python3 syntax, but I thought they were backwards-compatible.

What error are you getting?

**Comment by ChaoShenzjs** [comment]
g++ -g -O2 -O3 -std=c++14 -fopenmp -Wall -DOMP -ffast-math -ftree-vectorize   -c -fmessage-length=0 -MMD -MP -MF "utils.d" -o "utils.o" "utils.cpp"
g++: error：unrecognized command line option ‘-std=c++14’

**Comment by josephwb** [comment]
Sorry you are having problems.

This seems to be an issue with your C++ compiler. What does `g++ --version` return?

**Comment by ChaoShenzjs** [comment]
Thanks, I realized that my gcc version is too lower and needed to update.

**Comment by ChaoShenzjs** [comment]
Hi,
I have updated the gcc and g++ version in my environment and also installed armadillo dependency using source in phyx/deps directory. But terminated at the make step in phyx/src, showwing: In file included from rate_model.cpp:5:
rate_model.h:4:10: fatal error: armadillo: No such file or directory
    4 | #include <armadillo>

**Comment by josephwb** [comment]
Did you do the armadillo installation step? Which OS are you using?

**Comment by ChaoShenzjs** [comment]
My OS is Centos7 and didthe armadillo installation step.￼

**Comment by josephwb** [comment]
Hrm. Which version of armadillo are you using? You need version >= 5.2. Did it install with no warnings? Do you have [all of the dependencies](https://github.com/FePhyFoFum/phyx/blob/master/README.md?plain=1#L179) installed?

**Comment by ChaoShenzjs** [comment]
Hmm, I have checked the dependencies and some were lost, unfortunately, it always causes some troubles to install these dependencies by apt-get or source code. I find that phyx could be install through conda but with a OS environment for Python3. You know that I wanna phyx as a dependencies for the phylogenetic pipeline of Yang & Smith, 2014, MBE. However, their scripts were written in Python27, which is incompatible when running the pipeline. A easier way is that I could install phyx by conda in python27. I think it’s a heartfelt wish for new learner who wants to use this pipeline.
Best regards! Thank you so much!

**Comment by josephwb** [comment]
Phyx doesn't use python code, though; it is C++. The only time python is involved is as a wrapper for testing (and generating manpages), and really that it is for the developers to make sure things are not broken after code pushes.

The Y&S paper is almost 10 years old, so it is not surprising that some things do not work. Python2 was officially deprecated 3 years ago, which was about when we changed the syntax of our phyx tests. If you know python well it would not be too difficult to update Y&S to python3. It may even be as simple as changing the `print` calls; in fact, that was about the only thing done to our tests to 'upgrade' them to python3.

But the python version issue is really unrelated to building/running phyx. It seems that the compiler cannot find where armadillo is installed. Do you know where it was installed? If so you can 1) [add an alias to your .bashrc file](https://stackoverflow.com/a/19327832/3389183) or 2) [export your library path](https://stackoverflow.com/a/49436825/3389183).

Let me know if that works.

**Comment by josephwb** [comment]
Can I close this @ChaoShenzjs?
