### ISSUE TITLE
pxaa2cdn -r (again)

### ISSUE THREAD

**Issue by NatJWalker-Hale** [FePhyFoFum/phyx#177]
Hi Joseph,

Not actually an issue this time, but maybe a feature request. Because of transcriptome data, I not uncommonly deal with mixtures of complete and incomplete transcripts, i.e. some with stop codons and some without. In this case, `-r` works for sequences with stop codons, but also trims the last (legitimate) codon for those without, which then produces a length mismatch.

Of course, this is kind of an edge case and I can always just use a separate script to drop the stop codons from the complete transcripts, but I wonder if you might consider having `-r` (or perhaps a separate option), actually recognise `[TAG, TGA, TAA]` and remove them if present?

Thanks,

Nat

**Comment by josephwb** [comment]
I will look at this today. Could you provide an example input file?

**Comment by NatJWalker-Hale** [comment]
Sure - here is a simple two-sequence example case (taken from a larger alignment, hence the gaps).

[tmp.pep.aln.txt](https://github.com/FePhyFoFum/phyx/files/11982386/tmp.pep.aln.txt)
[tmp.cds.txt](https://github.com/FePhyFoFum/phyx/files/11982387/tmp.cds.txt)
[tmp.cds.aa2cdn.aln.txt](https://github.com/FePhyFoFum/phyx/files/11982388/tmp.cds.aa2cdn.aln.txt)

`pxaa2cdn -a tmp.pep.aln -n tmp.cds -o tmp.cds.aa2cdn.aln` gives

```
Error: for taxon 'Bvulgaris_548_EL10_1_0@14052' nucleotide alignment involves 544 codons, but protein alignment involves 543 amino acids. Skipping.
```
while `pxaa2cdn -r -a tmp.pep.aln -n tmp.cds -o tmp.cds.aa2cdn.aln` gives

```
Error: for taxon 'LDEL@61442' nucleotide alignment involves 564 codons (after removing final codon), but protein alignment involves 565 amino acids. Skipping.
```

Ideally, the latter would recognise the absence of a stop codon in LDEL@61442 and not remove the last codon, then align it instead of skipping it.

**Comment by josephwb** [comment]
I hope to get to this today. Sorry for the delay.

**Comment by NatJWalker-Hale** [comment]
Hey, sorry for slow response. Thanks so much for implementing! I guess it makes sense to keep `-r` just in case there are non-stop codon reasons people want to remove the last codon? I can't think what those would possibly be, but it's always good to keep flexibility.

**Comment by josephwb** [comment]
Kewl, thanQ.

**Comment by NatJWalker-Hale** [comment]
One last thing from a different set of testing - would it be possible to have lowercase sensitivity (even thought it is not standard)? I have some datasets with some sequences in lowercase mixed in (e.g. where the tail end comes from repeat-masked section). Would be great to have the stop codons be `[TAA, taa, TGA, tga, TAG, tag]`, but appreciate it is a weird request and reasonable to expect all upper.

**Comment by josephwb** [comment]
Yup, that is easily doable. Will take 2 minutes when I get a chance today. In the meantime programs like `pxs2fa` etc. have a `-u` uppercase export option. But like I said, I'll get to this in a bit.

**Comment by josephwb** [comment]
Should be working with [9c46bce](https://github.com/FePhyFoFum/phyx/commit/9c46bceebc439c9281e6214ea7fb569b6742ee4a). Probably good to have the case supported in case ones file contains _all_ lowercase.
