### ISSUE TITLE
infinite loop in superdouble implementation with gcc 13

### ISSUE THREAD

**Issue by emollier** [FePhyFoFum/phyx#178]
Hi,

Since introduction of gcc 13 in Debian sid, the _run_tests.py_ script hangs at the "character: 2" message after building _phyx_:
```
cd src && python3 run_tests.py
character: 0
character: 1
character: 2
```

Running _top_ reveals a _pxstrec_ process running at 100% cpu.  Attaching the hung _pxstrec_ process with _gdb_ reveals the process seems to be caught in an infinite loop during a _superdouble_ calculation:
```
0x0000560c29677683 in Superdouble::adjustDecimal (this=<optimized out>) at ./src/superdouble.cpp:40
40	        while (std::abs(mantissa) >= 10) {
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) step
41	            mantissa *= 0.1;
(gdb) 
40	        while (std::abs(mantissa) >= 10) {
(gdb) 
std::abs (__x=-inf) at /usr/include/c++/13/bits/std_abs.h:80
80	  { return __builtin_fabsl(__x); }
(gdb) 
40	        while (std::abs(mantissa) >= 10) {
(gdb) 
0x0000560c29677679 in std::abs (__x=-inf) at /usr/include/c++/13/bits/std_abs.h:80
80	  { return __builtin_fabsl(__x); }
(gdb) 
41	            mantissa *= 0.1;
[...]
```

On first sight, this looks to be related to excess precision changes documented in [porting to gcc 13] guide.  Adding _-fexcess-precision=fast_ per recommendation didn't help though.  Nevertheless, I managed to get rid of the issue by removing _-ffast-math_ for information, but maybe this is hiding something else:
```patch
--- phyx.orig/src/Makefile.in
+++ phyx/src/Makefile.in
@@ -35,8 +35,6 @@
     OPT_FLAGS += -ftree-vectorize
     ifneq ($(filter @host_cpu@,i386 i486 i586 i686),)
         OPT_FLAGS += -ffloat-store
-    else
-        OPT_FLAGS += -ffast-math
     endif
 endif
 
```

This has been seen on Debian sid with phyx 1.3 with gcc 13.1.0, and phyx 1.3.1 with gcc 13.2.0.  The issue is also loosely tracked in [Debian Bug#1037817].

[porting to gcc 13]: https://gcc.gnu.org/gcc-13/porting_to.html
[Debian Bug#1037817]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1037817

**Comment by josephwb** [comment]
Thanks for reporting this, and taking a look into the cause. 

I'll look at this in the next week, although I did not write this code. I imagine your Makefile fix will be sufficient.

**Comment by josephwb** [comment]
Removing `-ffast-math` doesn't _seem_ to break anything (at least from the `make check` standpoint). I'll do some code spelunking, but this may be a suitable solution.

**Comment by josephwb** [comment]
Removing `-ffast-math` doesn't _seem_ to break anything (at least from the `make check` standpoint). I'll do some code spelunking
