### ISSUE TITLE
Unable to ./configure

### ISSUE THREAD

**Issue by harsimranpadam** [FePhyFoFum/phyx#179]
I have downloaded phyx using simple instructions on my Mac (M1 processor), and it goes smoothly until I have to use the "./configure" command. It says: 
configure: error: cannot find required auxiliary files: config.guess config.sub
Can I do something to resolve this?

**Comment by josephwb** [comment]
Hrm. Try

autoreconf -fi

and try configure again.

**Comment by josephwb** [comment]
Make sure you have autoconf installed. Let me know if that works. 

Being on a mac, you should probably install via homebrew.

**Comment by harsimranpadam** [comment]
I installed it using the binary code and I didn't know if that would work perfectly on my computer, as it is a dependency for PyPHLAWD. So I wanted to make sure.
Your suggestion of:  "autoreconf -fi"  worked perfectly. Thank you very much for that.

**Comment by josephwb** [comment]
Yay! Good luck.
