### ISSUE TITLE
autoconf error in installation

### ISSUE THREAD

**Issue by laluciav** [FePhyFoFum/phyx#181]
Following the Homebrew installation in the last step when installing phyx:
autoconf give error:
-bash: autoconf: command not found

is there something missing? Can I do something to solve it?

**Comment by laluciav** [comment]
I already install autoconf by brew. And it says:
configure: error: cannot find required auxiliary files: config.guess config.sub

**Comment by josephwb** [comment]
I would've thought brew would have handles all of the dependencies. Are you on mac or linux? What happens when you type:
```
brew install brewsci/bio/phyx
```

**Comment by laluciav** [comment]
I am in mac. If run it I got:
Error: phyx: Failed to download resource "hwloc"
Download failed: https://ghcr.io/v2/homebrew/core/hwloc/blobs/sha256:8cfe9f6649200e089460520a32d6a947418a0dc6376eb9f4597c95bda0a73723

**Comment by josephwb** [comment]
I will try to get my hands on a mac and do a fresh install.

**Comment by josephwb** [comment]
@laluciav I got hold of a mac. I removed homebrew completely and installed phyx. If you only installed homebrew to get phyx then you should probably do a fresh install too. It only took a few minutes. I should note the homebrew install script in the phyx README was out of date.

```
# remove homebrew completely (https://mac.install.guide/homebrew/5.html). requires password
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"

# install homebrew. requires password
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# install phyx
brew install brewsci/bio/phyx
```
I've attached the [phyx_install.log](https://github.com/FePhyFoFum/phyx/files/13502443/phyx_install.log) so you can see what it should look like. As you can see, you need not muck around with autoconf etc.; those instructions deal with compiling it yourself using the phyx github repo.

Please let me know if this works.
