### ISSUE TITLE
Phyx errot: double free or corruption (!prev)

### ISSUE THREAD

**Issue by Cactusolo** [FePhyFoFum/phyx#184]
Hi,

We have been using phyx to subset a bunch of smaller trees, using`pxrmt` with `-f`, no matter use `-c` or not, the function giving errors like below:

```
pxrmt -t backbone.tre -f Clade1_2_backbone.txt -c
(((((Clematis_terniflora:5.3623700000000003,Clematis_crassfolia:5.3623700000000003):1.9920690000000001,(Clematis_huchouensis:4.8789850000000001,Clematis_fusca:4.8789850000000001):2.4754529999999999):0.942963,(Clematis_loureiriana:5.1261729999999996,Clematis_smilacifolia:5.1261729999999996):3.1712289999999999):12.3568939999999987,?L?|?U_viridis:0):11.8255459999999992,P@?|?U:0);
double free or corruption (!prev)
Aborted (core dumped)

```

The file are:
### Clade1_2_backbone.txt :  
Clematis_huchouensis
Clematis_fusca
Clematis_terniflora
Clematis_crassfolia
Clematis_loureiriana

### backbone.tre:  
(Anemoclema_glaucifolium:20.654295,(((((Clematis_reticulata:5.834076,(Clematis_huchouensis:4.878985,Clematis_fusca:4.878985):0.955090):1.520363,(Clematis_terniflora:5.362370,(Clematis_armandi:2.903558,Clematis_crassfolia:2.903558):2.458812):1.992069):0.942963,(Clematis_loureiriana:5.126173,Clematis_smilacifolia:5.126173):3.171229):0.531348,((Clematis_macropetala:2.218691,Clematis_sibirica:2.218691):3.233057,(((Clematis_repens:2.225859,Clematis_otophora:2.225859):1.719178,(Clematis_tibetana:2.918361,Clematis_glauca:2.918361):1.026675):0.454329,((Clematis_viridis:2.714744,Clematis_fruticosa:2.714744):0.946418,Clematis_songarica:3.661162):0.738204):1.052382):3.377002):0.536311,(((Clematis_rehderiana:4.684048,(Clematis_lasiandra:3.250204,Clematis_leschenaultiana:3.250204):1.433844):4.343206,((Clematis_aureolata:6.213598,Clematis_pilulifera:6.213598):2.734910,(((Clematis_brevicaudata:1.809052,Clematis_gratopsis:1.809052):0.504865,(Clematis_peterae:1.820023,Clematis_gouriana:1.820023):0.493894):0.355531,(Clematis_heracleifolia:1.984143,(Clematis_tubulosa:1.761059,(Clematis_speciosa:1.494645,Clematis_psliandra:1.494645):0.266414):0.223084):0.685305):6.279060):0.078746):0.155058,(Clematis_montana:2.571439,Clematis_chrysocoma:2.571439):6.610873):0.182749):11.289235);

I have googled, it seems to related to handling memory in C. Please help! Thanks!

Miao

**Comment by josephwb** [comment]
Hrm. I run the command with no issues:
```
$ pxrmt -t backbone.tre -f Clade1_2_backbone.txt 
(Anemoclema_glaucifolium:20.6542950000000012,((((Clematis_reticulata:7.3544389999999993,Clematis_armandi:7.3544389999999993):0.942963,Clematis_smilacifolia:8.2974019999999999):0.531348,((Clematis_macropetala:2.2186910000000002,Clematis_sibirica:2.2186910000000002):3.2330570000000001,(((Clematis_repens:2.2258589999999998,Clematis_otophora:2.2258589999999998):1.7191780000000001,(Clematis_tibetana:2.918361,Clematis_glauca:2.918361):1.026675):0.454329,((Clematis_viridis:2.714744,Clematis_fruticosa:2.714744):0.946418,Clematis_songarica:3.661162):0.738204):1.0523819999999999):3.3770020000000001):0.536311,(((Clematis_rehderiana:4.6840479999999998,(Clematis_lasiandra:3.2502040000000001,Clematis_leschenaultiana:3.2502040000000001):1.4338439999999999):4.3432060000000003,((Clematis_aureolata:6.2135980000000002,Clematis_pilulifera:6.2135980000000002):2.7349100000000002,(((Clematis_brevicaudata:1.8090520000000001,Clematis_gratopsis:1.8090520000000001):0.504865,(Clematis_peterae:1.8200229999999999,Clematis_gouriana:1.8200229999999999):0.493894):0.355531,(Clematis_heracleifolia:1.984143,(Clematis_tubulosa:1.7610589999999999,(Clematis_speciosa:1.494645,Clematis_psliandra:1.494645):0.266414):0.223084):0.6853050000000001):6.2790600000000003):0.078746):0.155058,(Clematis_montana:2.5714389999999998,Clematis_chrysocoma:2.5714389999999998):6.6108729999999998):0.182749):11.2892349999999997);
```
I am using pxrmt v1.3. I did an overhaul a while ago. Is your version up-to-date?

**Comment by Cactusolo** [comment]
Thanks for reminding! @josephwb 

Indeed, the version on my end is an older one `v1.1` from `conda` platform.  I'll try to install it manually if I can mange all the environments and dependencies.  :P

I'll let you know.

Miao

**Comment by josephwb** [comment]
Ok. Sorry for the troubles. I cannot think what the problem might be ¯\_(ツ)_/¯

**Comment by Cactusolo** [comment]
Ok, the update complete when I have to update the system :P

![image](https://github.com/FePhyFoFum/phyx/assets/7811840/c94cc128-4ebb-40d7-a128-c784a0f9c941)
