### ISSUE TITLE
pxclsq requires revised definition of missing data threshold

### ISSUE THREAD

**Issue by BenKuhnhaeuser** [FePhyFoFum/phyx#188]
When testing the tool `pxclsq`, I found that the missing data threshold appears not to be p, but 1-p. The wiki states that missing data > p are removed. This suggests that a smaller p value would be stricter, but the opposite seems to be the case.

I've done the following test with an alignment with 855 sequences and length 957:
-p 0.2: sequence length 957
-p 0.8: sequence length 384
-p 0.2 -t: 773 sequences
-p 0.8 -t: 410 sequences

An update in wording or code would be great to avoid confusion, thanks!

**Comment by josephwb** [comment]
Yikes! I will take a look at this. Thanks for bringing it up!

**Comment by josephwb** [comment]
@BenKuhnhaeuser I _believe_ it is working as advertised. Here is what the help states:
```
$ ./pxclsq -h

Clean alignments by removing positions/taxa with too much ambiguous data.
This will take fasta, fastq, phylip, and nexus formats from a file or STDIN.
Results are written in fasta format.

Usage: pxclsq [OPTIONS]...

Options:
 -s, --seqf=FILE     input sequence file, STDIN otherwise
 -p, --prop=DOUBLE   proportion required to be present, default=0.5
 -e, --empty         remove columns that are completely empty (- or ?)
...
```
So `pxclsq` look at things site-wise, and requires a proportion (`-p`) of character states within that column to be present to retain the column in the 'cleaned' output. So when we say `-p 0.2` _at least_ 20% of the character states in that column must be valid; likewise for `-p 0.8`. So the later is more restrictive (i.e., more valid character states present), and so we would expect fewer sites to conform. We should always see outputs to be _shorter_ in length when `-p` is increased (unless no invalid states are present, in which case the lengths should be the same).

Here is a tiny illustration with the example data:
```
josephwb@PotipharBreen:src$ ./pxclsq -s TEST/Alignment -p 0.25 | pxlssq -c
82
josephwb@PotipharBreen:src$ ./pxclsq -s TEST/Alignment -p 0.6 | pxlssq -c
42
```

82 sites have at least 25% valid states, but only 42 sites have at least 60% valid states.

Does this make sense? I can certainly make the help more clear.

**Comment by josephwb** [comment]
Gah I missed that you were doing per-taxon. Let me check again.

**Comment by josephwb** [comment]
No, it still hold. `-p` is the proportion of 'good' data present, not the proportion of 'bad' data. So (giving _some_ bad data present) increasing `-p` should always return smaller alignments.

I think the help could be better worded to reflect that. I will come up with something and run it by you here, kay?

**Comment by BenKuhnhaeuser** [comment]
What got me confused is the wiki, which states:
"Remove alignment sites based on proportion of missing data (-p). By default, removes individual sites from all sequences. Alternatively, missing data can be considered by codon (-c) or by taxa (-t, where entire sequences with missing data > p are removed)."

The phrasing "missing data > p are removed" suggests to me that a small p value would result in more data removed, hence the confusion! A few extra words in the help and a rephrasing in the wiki should do the trick.

Yes, more than happy to feed back on any revised wording.

**Comment by josephwb** [comment]
Ah. The wiki does not get updated as often as it should, and it seems things diverged. Sorry about that. I still think the help itself could be made clearer, but I'll endeavour to look at the entire wiki as well.

**Comment by josephwb** [comment]
This is what the help currently looks like:
```
josephwb@PotipharBreen:src$ ./pxclsq -h

Clean alignments by removing positions/taxa with too much ambiguous data.
NOTE: proportion/count args are in terms of VALID states, not ambiguous states.
This will take fasta, fastq, phylip, and nexus formats from a file or STDIN.
Results are written in fasta format.

Usage: pxclsq [OPTIONS]...

Options:
 -s, --seqf=FILE     input sequence file, STDIN otherwise
 -p, --prop=DOUBLE   proportion of valid character states required to be present, default=0.5
 -e, --empty         remove columns that are completely empty (- or ?)
 -m, --min=INT       the minimum number of valid character states required per site
                       - a min of 1 is equivalent to -e above
 -t, --taxa          consider missing data per taxon (default: per site)
 -c, --codon         examine sequences by codon rather than site
                       - requires all sequences be in frame and of correct length
 -i, --info          report counts of missing data and exit
                       - combine with -t to get report by taxon (rather than site)
                       - combine with -c to use codons as units
 -v, --verbose       more verbose output (i.e. if entire seqs are removed)
 -o, --outf=FILE     output fasta file, STOUT otherwise
 -h, --help          display this help and exit
 -V, --version       display version and exit
 -C, --citation      display phyx citation and exit

Report bugs to: <https://github.com/FePhyFoFum/phyx/issues>
phyx home page: <https://github.com/FePhyFoFum/phyx>
```
I think this is an improvement.

I realize that the wiki is what mislead you, and I made another issue specifically for that (#189). So I am going to close this issue. Please re-open if you are not satisfied.

**Comment by josephwb** [comment]
I guess I forgot to push this? Anyway, it is there with 10ee788
