### ISSUE TITLE
pxbd time

### ISSUE THREAD

**Issue by blackrim** [FePhyFoFum/phyx#2]
There is an error in the time calculation for the birth death calculator that gets negative branch lengths

**Comment by josephwb** [comment]
Do you have an example that will generate this (b, d, e/t, and seed)?

**Comment by blackrim** [comment]
how do you mean? birth death extant time and seed? can only do birth death
time seed or birth death extant seed
should be pxbd -b 1 -d 0.1 -t 5 -s 1 or pxbd -b 1 -d 0.1 -e 5 -s 1

**Comment by josephwb** [comment]
Yeah, the "e/t" was supposed to mean e _or_ t.

I just meant a combination that generates negative branch lengths so it could be identified and fixed.

**Comment by blackrim** [comment]
Oh, I see. I don't have an example that does that.

**Comment by josephwb** [comment]
Ok, I can set up a loop to try and find an example.

**Comment by josephwb** [comment]
I tried a bunch of iterations of:
```
./pxbd -b 0.5 -d 0.45 -e 10000 -o oot.tre && grep ":-" oot.tre
```
(including different parameter values) and cannot recreate the problem.

**Comment by josephwb** [comment]
`pxbd` now has a `nreps` option:
```
./pxbd -h
Birth-death simulator.

Usage: pxbd [OPTION]... 

 -e, --extant=INT    number of extant species, alt to time
 -t, --time=INT      depth of the tree, alt to extant
 -b, --birth=DOUBLE  birth rate, default=1
 -d, --death=DOUBLE  death rate, default=0
 -n, --nreps         number of replicates, default=1
 -o, --outf=FILE     output file, stout otherwise
 -s, --showd         show dead taxa
 -x, --seed=INT      random number seed, clock otherwise
     --help          display this help and exit
     --version       display version and exit
```
This should help in the search for negative edge lengths. However, I've simulated a ton and have not hit anything yet.

**Comment by josephwb** [comment]
I think this is behaving correctly. Closing.
