### ISSUE TITLE
pxstonex output calls Amino Acid Files dna

### ISSUE THREAD

**Issue by jfwalker** [FePhyFoFum/phyx#20]
./pxstonex -s cluster1061.fa.nuc

[cluster1061.fa.nuc.zip](https://github.com/FePhyFoFum/phyx/files/208560/cluster1061.fa.nuc.zip)
[cluster1061.fa.zip](https://github.com/FePhyFoFum/phyx/files/208561/cluster1061.fa.zip)

**Comment by josephwb** [comment]
Works fine for other fasta files. I thought it might have been the mixed casing, but now I think it is because in that one the sequences are of (vastly) different lengths.

**Comment by josephwb** [comment]
I will fix the "AA as DNA" bug.

**Comment by josephwb** [comment]
This is fixed with 966a0c99c6d5e0a1f8a0805c4b6dc2a191f85223.
