### ISSUE TITLE
pxconseq does not work with lower case

### ISSUE THREAD

**Issue by jfwalker** [FePhyFoFum/phyx#22]

**Comment by josephwb** [comment]
Doesn't work how? Segfault, or incorrect results?
Are you sure that you tried an example file where all sequences were the same length?

**Comment by josephwb** [comment]
It works for me with lowercase. Maybe you tried an amino acid alignment? As far as I can see, although it specifies `int alpha: the alphabet with 0=dna, 1=aa`, only DNA is implemented.

**Comment by jfwalker** [comment]
That might be the issue because it is working for me now with a nucleotide alignment

**Comment by josephwb** [comment]
Yeah, because there is a `inc = toupper(inc);`, so casing should not be a problem.

**Comment by josephwb** [comment]
I will just write the amino acid part.

**Comment by josephwb** [comment]
This (7440c5ce16fe492d32be190a0b471fddfba359a2) should do it. It makes use of the infer sequence type code added recently, so user does not have to specify what kind of alignment is involved.

Needs testing though!

**Comment by jfwalker** [comment]
The only issue I can find is that if the AA seq has missing data as '-' in it, then the consensus will call that 'N' instead of 'X'

**Comment by josephwb** [comment]
That is what the DNA consensus does, so I just assumed AA would be the same. Easy to change.
