### ISSUE TITLE
pxcat seems slow

### ISSUE THREAD

**Issue by josephwb** [FePhyFoFum/phyx#37]
Potential ways to make faster:
1. eliminate unnecessary object creation/destruction
2. two-passes over files?

**Comment by blackrim** [comment]
What are the stats on this?

**Comment by josephwb** [comment]
11 minutes for 17k files.

**Comment by blackrim** [comment]
What is the avg size of the files or the total size?

**Comment by josephwb** [comment]
17871 files, total of 310 MB.

**Comment by josephwb** [comment]
Two-passes will probably be much worse, as files would have to be opened, read, and closed two times each. The idea was to learn pattern of absence on first pass, do real work on second. I don't think this will work.

Getting rid of the unnecessary object creation seems easier and necessary.

**Comment by blackrim** [comment]
OK, I am going to go for this.

**Comment by josephwb** [comment]
Hrm closing this until it arises again (I am unaware of an example).
