### ISSUE TITLE
Some programs segfault when run without arguments

### ISSUE THREAD

**Issue by josephwb** [FePhyFoFum/phyx#42]
Noted during review:

>More informative error messages would help, in addition to suggesting the use of the `--help` flag. `--help` arguments from the repo and the manual don't match perfectly (see below).

**Comment by blackrim** [comment]
This has started to get fixed with 8799b2f3de68f868c592afb15c6b5e7ef4a9e826. Getting there

**Comment by blackrim** [comment]
done 593ff87
