### ISSUE TITLE
Manual overhaul

### ISSUE THREAD

**Issue by josephwb** [FePhyFoFum/phyx#43]
Noted in review. I admit I do not like working with a Word document; markdown or latex would be easier. The example setup is a bit clunky and hard to manage, too.

#############################

Manual:

The manual is off to a great start, but needs to be brought in sync with the current state of the repo -- e.g. folder names don't match and some programs appear to be missing. Perhaps it's an out-of-date LaTeX pdf?

The current repo stores examples in in `./example_files/` not `./Example/`

Manual example folders missing from repo:
`pxaatocdn_example` missing
`pxconsq_example` missing
`pxs2fa_example` missing
`pxs2nex_example` missing
`pxs2phy_example` missing
`pxvcf2fa_example` missing
`pxt2new_example` missing

Manual example names that mismatch repo folder names:
`pxnw` to `pxnw_example`
`pxsw` to `psxw_example`
`pxtlate` to `pxtlate_example`
`pxbp` to `pxbp_example`
`pxmrca` to `pxmrca_example`
`pxnni` to `pxnni_example`

Missing programs
`pxnni`
`pxtscale`

pg9
The program options are out of date when compared to `pxrms --help`.

pg10
`-r List.txt` to `-f List.txt`

pg13
I couldn't determine out what the output from `pxmrca` meant (although I did finally figure out who KIM, LEE, and THURSTON were). Maybe add more description to the manual and --help output.

pg14
Not sure what `pxmrcacut` does, but I could not view the output Newick string in FigTree or plot it in R using ape.

pg22
The `pxcontrates` example gave me nan values when using the provided files

**Comment by josephwb** [comment]
Most of this is done (and thanks to @jfwalker for redoing this in latex format!).

I have not touched on the last thing yet:
>The pxcontrates example gave me nan values when using the provided files

**Comment by josephwb** [comment]
I think we can considered this completed.

**Comment by Cactusolo** [comment]
Sorry, I can find a good place to ask this question, and it's not a issue.:

for the function "pxconsq" in phyx, the manual says that "the consensus sequence"; but I can't figure out  the "the consensus sequence" is strictly consensus or MJR consensus? If this could explained in the manual or can provide different flavors (or use defined consensus threshold) should be great.


Thanks!

Miao

**Comment by josephwb** [comment]
I suppose it would be considered strict for DNA: IUPAC ambiguity codes are used to represent all bases present at a site (try ```pxconsq -s TEST/test.fa``` in the ```src``` directory for an example). Not sure what happens with AAs.

**Comment by josephwb** [comment]
Hrm there may be a bug here. The first site in the example (A,G,A,T,T) should be 'D', but 'R' (A.G) is reported. The next few sites are correct. But this should be examined in detail.

**Comment by josephwb** [comment]
Ok I fixed that one (missing condition). The rest seem fine, but will test thoroughly later today.

**Comment by Cactusolo** [comment]
@josephwb Also, for the output: 

Is it possible to have a flag (or option) that user can choose preferred symbol for gap? 
Like "-" or "N", or no gap generated in the consensus sequence (like the strict major rule consensus in Geneious? 

I think these are useful when assembling target enrichment data, where people want consensus sequence for each gene as reference. So the direct `pxconsq` results will meet the need (current output containing too many Ns).

**Comment by josephwb** [comment]
Sure. We would need to know the permutations that would be desired. For example, if one sequence has A and all the rest gaps, should the consensus be A or - (or something else)? It is also not rare to have both N (ambiguity) _and_ - (gap) within a single sequence. If all sequences are a gap at a site, are you suggesting dropping the site from the consensus completely?

Happy to do whatever you'd like. Maybe start a fresh issue to elaborate on things. Maybe provide a small example input and expected output(s).

**Comment by Cactusolo** [comment]
Thanks! Will do.
