### ISSUE TITLE
Unittests

### ISSUE THREAD

**Issue by josephwb** [FePhyFoFum/phyx#44]
Noted in review:
## Tests

-   Unfortunately, neither the publication nor the manual make mention of any unitttests or indeed tests of any kind. Furthermore, looking at the repository, there is also no evidence of tests of any kind.
-   I am afraid that I cannot recommend this software for publication without demonstration and documentation of tests. There is no reason for academic software to be held to lower standards that any other kinds of software. This software will be used by people who do not know about the internals of the code, and the results of THOSE people's work, in turn, will be cited/used by other people who may not know about the programs in th first place. At each stage there is trust in that certain critical internals have been given due diligence and care by the previous stage. This trust is essential to our community. When it comes to software development, the trust is in the form that the programs are doing what the authors claim that the programs are doing. Validating  that this is indeed the case (and demonstrating that validation) is the authors' responsibility to the community, especially if they are aiming to gain citable academic publication out of this.
-   Tests should, at the very least, demonstrate that the programs are doing what they are supposed to do given some minimal canonical input. Testing C++ programs dealing with complex data like this is difficult, but certainly not only possible, but dedicatedly pursued by responsible authors (e.g., NCL, phycas).
-   I recommend testing input/ouput (e.g., by round-tripping data files and ensuring content remains as expected) explicitly and separately from manipulations and operations.
-   With the latter, simple examples from the manual/documentation/paper for each one will do to start.
-   In all cases, if semantic-checking of output is too challenging, a simple pattern matching will do (the latter is fragile, in that small tweaks to the programs' writers in terms of spacing, etc., will result in tests failing, but this can easily if tediously be fixed).
-   More advanced testing would be nice, e.g., for incorrect input and so on. But I recognize that this would be a lot of work and that authors may want to develop these later.

**Comment by blackrim** [comment]
I will be writing these. For now, they will be part of the make framework to test input and output (and so that `make test` will do this for the users). In the future, I will use googletest to do unit tests on individual functions. However, I will make a new issue when we get to that point

**Comment by blackrim** [comment]
These are starting to go up with this a420e359bc0c2cfe10c2235d217be08dff210183. Finishing them up now
