### ISSUE TITLE
Provide mac binaries?

### ISSUE THREAD

**Issue by josephwb** [FePhyFoFum/phyx#45]
Oi.

This would obviously be nice, but a _huge_ headache given, well, mac. The install instructions have worked across versions for us, but obviously not for a reviewer.

I will look into (somehow) producing binaries that are supported across multiple versions, but since I have never been able to do so in the past, I am not optimistic.

**Comment by blackrim** [comment]
Are you going to do this @josephwb ? I can assign you.

**Comment by josephwb** [comment]
Gah. Sure, I guess, but I think this is low priority (i.e. I have more pressing things right now).

**Comment by blackrim** [comment]
sounds good. i can try as well after i get the tests

**Comment by josephwb** [comment]
Decided to go with clearer install directions, as supporting multiple versions seems like a pain.
