### ISSUE TITLE
Master help?

### ISSUE THREAD

**Issue by josephwb** [FePhyFoFum/phyx#49]
@ningwang83 has mentioned that remembering what each program does is difficult (there are so many!). I wonder if we could use a "master help" program, like:
```
pxh
```
which prints out a _very short_ description of each program, and maybe an example command.

**Comment by blackrim** [comment]
I think I would have one that is `phyx` instead of `pxh`.

**Comment by josephwb** [comment]
Thoughts on this? Would it be useful?

**Comment by ningwang83** [comment]
Yes, it will definitely help. I talked to Tongjian, the visiting student in
the lab, and he also feel too many programs in there, better to have a
guide. Moreover, he felt the instructions should be better more detailed.
provide more example for each program could be a way to do this I think.

Thanks Joseph! I hope to use phyx more, now I'm using phyx to reroot,
change alignment format, align aa from cds etc. I know there are a lot of
cool programs inside, so looking forward to the guide!

Happy thanksgiving!

Ning

**Comment by josephwb** [comment]
Hmm... I am still not completely convinced :( It would be a _long_ (raxml-ish) help. Not too difficult to set up, but a pain to maintain (we already have individual helps, the manual, and the wiki). Why not just look at the manual? @jfwalker @blackrim?

**Comment by josephwb** [comment]
I don't think this is worth it. I've updated the README to give one-liner summaries of all the available programs. Together with the wiki (the manual is shite) this should be sufficient.
