### ISSUE TITLE
No example file given for how to supply a file-list of tips to pxrmt

### ISSUE THREAD

**Issue by rossmounce** [FePhyFoFum/phyx#51]
Just a small documentation suggestion.

It appears from the Phyxed_manual (2016-12-02) that the file formatting of the list of tips one can supply to `pxrmt` is undocumented. No example tips file is given in `phyx/example_files/pxrmt_example`.

Now obviously you & I might think it obvious that taxon names should be supplied in a file one per line c.f. `grep -f <PATTERN FILE>` and other unix classics:
```
s2
s4
s5
```
(and I infer from empirical testing that this is what it should be)

But other users might reasonably try and supply it a taxon file as a csv or tsv list 
```
s2,s4,s5
```

or say

```
s2|s4|s5
```

or other such schemes. So I think you should formally provide an example `tips-to-be-deleted.txt` file for `pxrmt`

**Comment by jfwalker** [comment]
We've update the examples in the past few days so there should be one if you pull again

**Comment by josephwb** [comment]
Thanks for the suggestion. The help is pretty clear on this:
```
pxrmt -h
This will remove tips from a tree file and produce newick
Can read from stdin or file

Usage: pxrmt [OPTION]... [FILE]...

 -t, --treef=FILE     input tree file, stdin otherwise
 -n, --names=CSL      names sep by commas (NO SPACES!)
 -f, --namesf=FILE    names in a file (each on a line)
 -o, --outf=FILE      output tree file, stout otherwise
 -s, --silent         suppress warnings of missing tips
 -h, --help           display this help and exit
 -V, --version        display version and exit
```
but i will update the manual.

**Comment by rossmounce** [comment]
Ah sorry, didn't think to try `pxrmt -h`

**Comment by josephwb** [comment]
I think this is fixed with https://github.com/FePhyFoFum/phyx/commit/34618fdf00e947e21130295ee90d5a64a678a6c4

**Comment by josephwb** [comment]
BTW we appreciate the issue reports! :hatched_chick:
