### ISSUE TITLE
Code Quality

### ISSUE THREAD

**Issue by kloetzl** [FePhyFoFum/phyx#53]
I'll just leave some issues here, which I found by briefly glimpsing over the source code.

- [`i` should be of type `size_t`](https://github.com/FePhyFoFum/phyx/blob/master/src/distmatrix.cpp#L23)
- [There is a constructor for that](https://github.com/FePhyFoFum/phyx/blob/master/src/distmatrix.cpp#L42-L45)
- [using a `float` as a boolean flag‽](https://github.com/FePhyFoFum/phyx/blob/master/src/distmatrix.cpp#L87)
- [old program name](https://github.com/FePhyFoFum/phyx/blob/master/src/main_nj.cpp#L38)
Also, `"separate" "string" "literals"` are treated as if they were one, but look more pleasing to the eye.
- [This looks fishy](https://github.com/FePhyFoFum/phyx/blob/master/src/seq_gen.cpp#L85-L93) Are you sure you need a `float const&` parameter instead of just a `float`?
- [Here you might want to consider a const ref](https://github.com/FePhyFoFum/phyx/blob/master/src/seq_gen.cpp#L253)
- [For constructors, take parameters by value and `std::move` them into members](https://github.com/FePhyFoFum/phyx/blob/master/src/sequence.cpp#L21)

Best,
Fabian

**Comment by josephwb** [comment]
Thanks!

**Comment by josephwb** [comment]
Most of these involved `distmatrix.cpp`, which isn't being used. I've made most of the other changes.

**Comment by kloetzl** [comment]
> Most of these involved `distmatrix.cpp`

Yeah, I just scanned a few files and compiled a list of issued. ☺
