### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by afif-elghraoui** [FePhyFoFum/phyx#54]
I'm considering packaging this for Debian, but I noticed that the latest release is very far behind the current master. Do you have plans to tag a new release soon, or is that release (0.9) the recommended version for us to use?

**Comment by josephwb** [comment]
No, we definitely need to make a new release (thanks for checking). I'll leave that to @blackrim

**Comment by blackrim** [comment]
done! Thanks @afif-elghraoui

**Comment by afif-elghraoui** [comment]
Many thanks! I've just filed an [intent-to-package phyx](https://bugs.debian.org/855597) over at Debian and got started on the packaging.
