### ISSUE TITLE
missing manpages

### ISSUE THREAD

**Issue by kloetzl** [FePhyFoFum/phyx#56]
phyx would profit from manpages. To get you started, I provided one for [pxlstr](https://github.com/kloetzl/phyx/blob/manpages/doc/pxlstr.1). Once #49 is done, that might be a useful entry point for users looking for help if it also gets a man page.

**Comment by kloetzl** [comment]
man pxlstr

**Comment by josephwb** [comment]
I understand. But is that better than `-h`? With the current configuration code and doc sit together. I'm worried if they ever get separated they have the potential to diverge.

**Comment by kloetzl** [comment]
As you try to be *UNIXy* I strongly suggest you provide a manpage. Your `-h` is great, but a manpage simply can offer more information. Also no one reads the docs. But manpages might help bring the documentation closer to the user.

**Comment by josephwb** [comment]
I have no interest in doing this. @blackrim if you want to do this, great. Otherwise, close this for now.

**Comment by josephwb** [comment]
I've changed my mind on this. Apologies all around.

This appears very easy. I hope to push man pages for all programs in the next day or two.

**Comment by kloetzl** [comment]
Ideally one would want to generate manpages and other documentation from each other/the same source. If you find a good solution to that, please let me know. ☺

**Comment by josephwb** [comment]
What I am using at present is `help2man`. It is partly because it seems so easy to use that I flipped my mind on this. I am exploring its functionality to see what is possible, but even the default settings generate decent results.

**Comment by josephwb** [comment]
An initial set of man pages exists as of df935cbfafe50141a8a5f544f6928d56bd4bc018. Still need to 1) vet these for content and 2) set things up to install these with their respective programs. East stuff; will complete in a day or two, and close this when merging to master.

**Comment by kloetzl** [comment]
:+1:
