### ISSUE TITLE
pxlstr arguments

### ISSUE THREAD

**Issue by kloetzl** [FePhyFoFum/phyx#57]
The help for `pxlstr` states *By default returns all properties. Alternatively choose 1 property.* However, this does not apply to the `-i` flag. It simple gets ignored, when combined with any of the other flags.

Also, when two arguments clash, I would suggest to exit with a non-zero status code to indicate an error.

**Comment by josephwb** [comment]
Thanks for finding that. I will make it consistent with the other properties.

**Comment by blackrim** [comment]
is this still open?

**Comment by josephwb** [comment]
Yeah, I have not fixed it yet.

**Comment by josephwb** [comment]
Fixed with 8ce082b
