### ISSUE TITLE
pxrls path in run_tests.py

### ISSUE THREAD

**Issue by dilut** [FePhyFoFum/phyx#58]
The command for pxrls in the test script (run_tests.py) is missing the relative path (./), so the shell fails to find it and the test script reports test failure for pxrls. The component (pxrls) runs successfully with the proper path.

**Comment by josephwb** [comment]
Nice catch! I guess we missed it because we had it installed. Thanks.

**Comment by josephwb** [comment]
Fixed with 1ad74c46bb63f55ea06b548012f27a0b996b5c24
