### ISSUE TITLE
problem rerooting tree if first outgroup listed isn't present

### ISSUE THREAD

**Issue by stubbsrl** [FePhyFoFum/phyx#61]
I am rerooting hundreds of gene trees. Most genes have any combination of outgroups. If the first outgroup listed in my command is not present instead of moving to the next outgroup listed it produces an empty file.

**Comment by stubbsrl** [comment]
Read through the closed issues and if I add a -s then it overwrites this problem. Maybe add this to the wiki?

**Comment by josephwb** [comment]
Yes, this is a newer option. I'll update the wiki.

**Comment by josephwb** [comment]
Updated in the wiki and manual.
