### ISSUE TITLE
Don't add zero edge lengths to cladograms

### ISSUE THREAD

**Issue by josephwb** [FePhyFoFum/phyx#62]
A little annoying when opening in FigTree and the tree collapses to a line because the "phylogram" has a length of zero.

Not a big deal or rush.

**Comment by josephwb** [comment]
Ok this seems on the surface to be extremely easy to do: `getNewick` has a boolean option on whether edge lengths should be included (which are set to 0 if they are not present).

So: how best to deal with this? There is a function `has_branchlengths` in `tree_utils` that can test this, and the result of this can be passed to `getNewick`. Seems wasteful tho. I think I will look at doing this upstream in `TreeReader` (reading things in anyway, just a simple check on the presence/sum).

Only question is: would we ever _want_ to export a tree with zero edge lengths? I cannot think of any reason.

**Comment by josephwb** [comment]
Ok I store during reading in whether edge lengths are present. Making a generic print function that will take advantage of this.

**Comment by josephwb** [comment]
Added a clunky way to do this in `pxrmk`. Think a wrapper function would save on a lot of typing.

**Comment by uribe-convers** [comment]
cool, thanks @josephwb!

**Comment by josephwb** [comment]
In `tree_utils` there is now a wrapper function `getNewickString` which detects stored boolean property `edgeLengths`. Edge lengths are written is present, otherwise a cladogram is born.
