### ISSUE TITLE
pxrr -s option error

### ISSUE THREAD

**Issue by HeatherKates** [FePhyFoFum/phyx#66]
Hello,

When I run the pxrr program with the -s option, I get various errors (depends on the run), including:
/apps/phyx/0.99/launch_phyx: line 12: 54412 Segmentation fault      singularity exec ${HPC_SINGULARITY_IMG}/phyx/0.99-xenial.img "$@"
/apps/phyx/0.99/launch_phyx: line 12: 55300 Segmentation fault      singularity exec ${HPC_SINGULARITY_IMG}/phyx/0.99-xenial.img "$@"

I am running phyx on a computing cluster and don't recognize these errors or know anything about the singularity app. I have also submitted a request with the computing cluster to see if they know what could be causing the error.

I don't get errors without the -s option, but there's no other way for me to run pxrr; I have 4 possible outgroups across 520 gene trees and if I use the -r option, any outgroups besides the one selected are pushed into the ingroup which is not accurate/creates problems with downstream comparisons. 

Any ideas about this error greatly appreciated.
Thanks!
Heather Rose

**Comment by josephwb** [comment]
Hi @HeatherKates. Sorry for the headache. Could you send a reproducible example?

**Comment by blackrim** [comment]
I am happy to tackle this. @HeatherKates do you have an example?

**Comment by HeatherKates** [comment]
Hello again, I'm sorry for not responding to your replies, I had a baby the next day and then here we are a year later. I don't recall how or if I resolved the issue above as it applied to that project, but I had the same error today and traced it back to using a set of outgroups that were non monophyletic. In this case I was not using the -s option because I am trying to reroot a single tree by the root of a clade by specifiying tip pairs like root_crown in treePL. I will submit this as a separate issue to avoid confusion as it may be an unrelated error with a same error message (or lack thereof), but wanted to let you close this issue since I'd left it open ended for so long.

**Comment by josephwb** [comment]
Congrats on the baby @HeatherKates!

Can you post an example input and expected output (output can be verbal)?

**Comment by josephwb** [comment]
I am closing this as we don't have a reproducible example. Please reopen if one surfaces.
