### ISSUE TITLE
de-knuckler (pxrmk) not working

### ISSUE THREAD

**Issue by uribe-convers** [FePhyFoFum/phyx#68]
I'm building a phylogeny using a taxonomic constraint tree, and this tree has knuckles that make RAxML choke. 

I tried: `pxrmk -t constraint.tre -o constraint_no_knuckles.tre`

Then: `raxmlHPC-PTHREADS-AVX -T 15 -p 9876 -m GTRCAT -g constraint_no_knuckles.tre -s alignment -n test` and get the following error (same error with the un-knuckled constraint tree): 
```
ERROR: Too many internal nodes.  Is tree rooted?
       Deepest splitting should be a trifurcation.
```

If I manually delete the first and last parentheses in the Newick file, RAxML works fine. Also, the tree that I get with `pxrmk` has zero branch lengths.

Here are the files I used:  
alignment, constraint.tre, and constraint_no_knucles.tre that I got with `pxrmk`

[Archive.zip](https://github.com/FePhyFoFum/phyx/files/1356920/Archive.zip)

**Comment by josephwb** [comment]
Just a reminder that the issue with adding zero-length edges is a, er, issue (https://github.com/FePhyFoFum/phyx/issues/62).

I wonder if this desired functionality (removing stem edges) should be put into `pxrmk` or a more general `check-tree-is-cool` program?

**Comment by josephwb** [comment]
Hey @uribe-convers. Apologies for letting this slip.

I don't believe the tree _has_ "knuckles" (i.e. 2-degree nodes), but _does_ have, as you say, an extra set of brackets at the outermost level; in other words it has a root edge. I would say that this is non-standardly constructed. Where did the come from?

I'm not sure what to do here... Should "remove root edge if present" be part of this program? I can think of some instances where you'd _want_ to retain a root edge (say, in a diversification rate experiment). Hmm...

**Comment by uribe-convers** [comment]
Hey @josephwb, Thanks for letting me know. 

The tree came from PyPHLAWD; it's the topological constraint tree that is pat of the output. It's ok, if this is not that common then there is no need to create a new feature in the program. 

Thanks for looking into it!

**Comment by josephwb** [comment]
Got it.

However, if in using PyPHLAWD you are coming across this repeatedly I'd want you to have something convenient to deal with it. I thought you might just be able to "unroot" it but that makes phyx die a fiery death:
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 1) >= this->size() (which is 1)
Abort trap: 6
```
Yikes!

I'll either add the option to `pxrmk` or write a separate "root annihilator".

**Comment by josephwb** [comment]
New issue https://github.com/FePhyFoFum/phyx/issues/73 should cover this.

**Comment by josephwb** [comment]
@uribe-convers new program `pxcltr` will get rid of superfluous root edges.

**Comment by josephwb** [comment]
I am going to close this bc I believe the de-knuckler is working correctly.
