### ISSUE TITLE
pxstrec not available

### ISSUE THREAD

**Issue by uribe-convers** [FePhyFoFum/phyx#69]

**Comment by josephwb** [comment]
Do you mean it is not _built_? It is in the default [make].(https://github.com/FePhyFoFum/phyx/blob/master/src/Makefile.in#L336)

I am trying a fresh clone/compile to check things.

**Comment by josephwb** [comment]
Do you mean it is not built? It is in the default [make](https://github.com/FePhyFoFum/phyx/blob/master/src/Makefile.in#L336).

I am trying a fresh clone/compile to check things.

**Comment by josephwb** [comment]
Try a fresh clone/compile.

On mac i use the homebrew C++ compiler by passing this to configure:
```
./configure CXX=/usr/local/bin/g++-7
```
Hopefully we can sort this out!

**Comment by josephwb** [comment]
Closing this as I believe it is a weird @uribe-convers-specific issue ( -_・)
