### ISSUE TITLE
Better uninstall?

### ISSUE THREAD

**Issue by josephwb** [FePhyFoFum/phyx#75]
This one has had me worried for a bit. Our current uninstall is:

```
uninstall:
        -$(RM) $(prefix)/px*
```

This works fine. _However_, what if there is another program/file in that directory that begins with "px"? Uninstalling phyx could break other things (which could be difficult to diagnose. I haven't run into this, but it seems like an eventuality).

The solution, I guess, is to store the names of all phyx programs so they can be deleted specifically. I'm not sure how this is typically done...

**Comment by josephwb** [comment]
This also involves install as well. I had a folder `pxrmt_trouble` and it messed up standard installation (it tried to copy the folder).

**Comment by blackrim** [comment]
Can we please just put the list of programs that are present? @josephwb or @blackrim can do it.

**Comment by josephwb** [comment]
Will think this over. These are stored in `all` in the Makefile. Can this be used? Probably.

**Comment by josephwb** [comment]
Kablammo :boom:
