### ISSUE TITLE
Error in pxrmt

### ISSUE THREAD

**Issue by stubbsrl** [FePhyFoFum/phyx#76]
I'm getting strange errors with pxrmt. I am using the command on files I have (successfully) used with pxrmt before. 

The general command I'm using is:
for x in bipartition_trees/R*; do pxrmt -t $x -n taxon1,taxon2,taxon3 -o $x.prune; done 

I've attached the error file.

Anyone else having trouble with this or is it just me? Thoughts on what's going on?

Thanks,
Rebecca

**Comment by josephwb** [comment]
@stubbsrl the error file is not attached.

**Comment by stubbsrl** [comment]
Right... Here ya go :) 

[phyx.pxrmt.15974891.err.txt](https://github.com/FePhyFoFum/phyx/files/1636890/phyx.pxrmt.15974891.err.txt)

**Comment by josephwb** [comment]
Yikes! Does it fail right away? If so, can you share a few of the files so we can recreate?

BTW did you reinstall since it had been working correctly?

**Comment by stubbsrl** [comment]
When run on the command line it starts spitting out errors right away but then it gets hung up on that last error and never officially fails.

Yes, the program has been reinstalled a few times since it was working correctly. Fun fact: when I run pxrmt on my computer (vs the HPC) I get different but similar errors. Mostly pertaining to segmentation faults (so I wondered if it was a memory problem and hence moved to HPC). 

I've attached a few tree files and the submit script with the full command I'm using (I'll remove them from this thread once you get them). 

Rebecca
[pxrmt_trouble.zip](https://github.com/FePhyFoFum/phyx/files/1636922/pxrmt_trouble.zip)

**Comment by josephwb** [comment]
Ok, thanks. I can reproduce it with tree 'RAxML_bipartitions.g005super_rmsn.stripped'. It _seems_ to produce a (correct?) tree but then segfaults. Interestingly it does not segfault if the last tip to prune is removed, although it definitely _is_ in the tree as determined by:

`pxlstr -t RAxML_bipartitions.g005super_rmsn.stripped -i`.

I will look at this tomorrow. Sorry for the troubles!

**Comment by josephwb** [comment]
That is, it seems to produce a (correct?) tree on mac. Linux produces nothing but an error.

Hopefully this will not be too difficult.

**Comment by stubbsrl** [comment]
Well not really (re: correct trees on mac). Of the five I sent you two end up as empty files. The other three aren't able to be open up in figtree because when I look at the file in a text editor there's some nonsense at the beginning of the file. Once I delete the nonsense the tree opens fine. 

On the HPC a similar things happens. Some files are empty. Some are created but have a nonsense string at the beginning of the file. 

As you may see the nonsense string is part of the name of one of the outgroups. If I remove that outgroup from my initial command (i.e., keep it in the tree) three trees are produced as empty files and the two other trees now open fine.

**Comment by josephwb** [comment]
@stubbsrl could you please resend the example files? The computer I was working on died :(

**Comment by josephwb** [comment]
@stubbsrl oof never mind i got it from email. :bowtie:

**Comment by josephwb** [comment]
@stubbsrl sorry for the delay. can you pull and try again?

**Comment by stubbsrl** [comment]
Hey Joseph - No problem. Really, thanks for all your help.

I did git pull. There were " 3 files changed, 18 insertions(+), 8 deletions(-)"

But, unfortunately, same results. Did you get this to work normally on either files? Is there a chance it is something wrong with my trees?

**Comment by josephwb** [comment]
Did you do `sudo make install`? If not, it will still be the earlier version. I have only been testing using the first tree. I will try with others.

**Comment by stubbsrl** [comment]
I navigated into the src folder and sudo make install there. Is that correct? If so, same problems occurred.

**Comment by josephwb** [comment]
I am in a meeting at the moment, but will investigate soon.

Can you try (in `src`):

```
git pull
sudo make uninstall
make clean
make
sudo make install
```

**Comment by stubbsrl** [comment]
Oh snap! It worked perfectly!!

I believe you fixed it! I'm going to have them update Phyx on the HPC too. 

Thank you!

**Comment by josephwb** [comment]
w00t! So glad it worked.
