### ISSUE TITLE
pxrmk

### ISSUE THREAD

**Issue by blackrim** [FePhyFoFum/phyx#81]
Getting a seg fault on this tree.
[t.tre.gz](https://github.com/FePhyFoFum/phyx/files/1956443/t.tre.gz)

**Comment by blackrim** [comment]
OK, the problem is the non newick stuff but we should fail more gracefully

**Comment by blackrim** [comment]
OK, it is the non-newick stuff but we need to fail more gracefully

**Comment by josephwb** [comment]
I cannot remember what the issue is with this tree. But other programs (e.g. `pxlstr`) cannot read it either.

**Comment by josephwb** [comment]
Oh yeah, spaces in taxon names was one problem. But not the only one (I think).

**Comment by josephwb** [comment]
Right. Not just spaces. I think there were weird (illegal) characters in names (commas or brackets or whatever).

**Comment by blackrim** [comment]
yeah, i am wondering if we can fail more gracefully instead of a segfault. do you know in the line where it is failing? don't have to spit out the diagnosis because that will likley be too hard, but should be able to say that there is a problem with one of the characters

**Comment by josephwb** [comment]
Yup. Right [here](https://github.com/FePhyFoFum/phyx/blob/master/src/tree_reader.cpp#L164-L167).

**Comment by blackrim** [comment]
It actually isn't failing on those spaces as far as I can tell. Definitely more complex. It catches it now though so that is what this issue was. There is an issue with this newick that i can't track. It won't read in figtree either (but the spaces are fine actually) 06a1a93
