### ISSUE TITLE
pxbp aborting

### ISSUE THREAD

**Issue by erikkoenen** [FePhyFoFum/phyx#86]
Hi
I'm trying to run pxbp over a large number of gene trees to extract bipartitions. I'm looping through the gene trees so every time pxbp is called to run on just a single tree. I'm using the -e option for unrooted trees. For several gene trees, the program doesn't print a list of bipartitions but instead I'm receiving either one of the following two error messages:
 
> free(): invalid pointer
> Aborted

or

> free(): invalid next size (fast)
> Aborted

In some cases, this only happens under a specific bootstrap cut-off as specified with -c.
What is going wrong here?

**Comment by josephwb** [comment]
Can you provide an example input that produces these errors?

**Comment by blackrim** [comment]
I believe this was just fixed with this commit https://github.com/FePhyFoFum/phyx/commit/a0b974101b59d08eec73ab30c8da7972fab157d0 so you should be able to pull and recompile pxbp and be good.

**Comment by blackrim** [comment]
I should have added that that commit was only a couple days ago as someone else also pointed out the issue to me
