### ISSUE TITLE
pxcontrates failing test

### ISSUE THREAD

**Issue by josephwb** [FePhyFoFum/phyx#88]
Seems like tree 1 is printed with values for character 1, tree 2 with values from characters 1 & 2, and tree three with values from all 3 characters. Test expected output is a single value per node. Seems like neither output is correct?

Apologies if I broke this (I seem to be the last to edit), but I cannot figure out what the issue is.

**Comment by blackrim** [comment]
OK, I guess I will track where the output changed because obviously it use to pass.

**Comment by blackrim** [comment]
fixed the output. also fixed the test so that it should be more consistent
f7f3e98
