### ISSUE TITLE
pxrr using root crown taxa

### ISSUE THREAD

**Issue by HeatherKates** [FePhyFoFum/phyx#94]
Hello, I'm trying to reroot a single tree by the root of a subclade. To do this, I tried specifying two outgroups that are root crown taxa for that clade. This did not work. Is there an option to do this? I don't want change the clade membership in the tree.

**Comment by josephwb** [comment]
Didjya figure this out @HeatherKates?

**Comment by HeatherKates** [comment]
For my purposes I did - the taxa were not root crown taxa for the clade I wanted to reroot with and I think I may have been asking for an impossible re-rooting. Though I would have expected the result to just be an unchanged tree instead of an error. 

If you do want to look at it, input file is attached and command is:
pxrr -t Supermatrix_2-22_constraint_50perc_tips_dropped.renamed.tree -g Astragalus_nobilis,Astragalus_sulcatus > Supermatrix_2-22_constraint_50perc_tips_dropped.renamed.rerooted.tree

[Supermatrix_2-22_constraint_50perc_tips_dropped.renamed.tree.txt](https://github.com/FePhyFoFum/phyx/files/2668710/Supermatrix_2-22_constraint_50perc_tips_dropped.renamed.tree.txt)

**Comment by josephwb** [comment]
Hi @HeatherKates. I ran the commands and the tree appears to be rooted as requested. Although, since the 2 taxa are so disparately related, it is rooted on their MRCA, and it is sister to another large clade. I do not get any error. I just ran:
```
pxrr -t Supermatrix_2-22_constraint_50perc_tips_dropped.renamed.tree.txt -g Astragalus_nobilis,Astragalus_sulcatus -o rr.tre
```
What error did you get? It is possible that we may have updated things since your last pull?

**Comment by HeatherKates** [comment]
The error is: /apps/phyx/0.99/launch_phyx: line 12:   614 Segmentation fault      (core dumped) singularity exec ${HPC_SINGULARITY_IMG}/phyx/0.99-xenial.img "$@"

It's very possible there's been an update, I'm running on a computing cluster and I think they just update when we request (and I haven't requested, not sure there are other users at the moment). I can't be 100% sure the input tree I sent is the exact one I used, I was making a lot of changes and sometimes overwriting intentionally, without being totally sure I don't want to narrow it down to the update, but I'll request one because that seems good in any case. If I run into the error again I will send the definite input data and command at that time. Thanks for your attention to this! Phyx is the best.

**Comment by josephwb** [comment]
"Singularity" is a pretty cool error. 
Ok. The input file _did_ have a slightly different name, so that could be it. The current release is v0.999, so that could be it (too?). I hope we can figure things out.
